"""completar seguridad y auditoria

Revision ID: 477ca20b3a43
Revises: 8d7a3ab2a65d
Create Date: 2026-09-26 23:06:04.003346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '477ca20b3a43'
down_revision: Union[str, Sequence[str], None] = '8d7a3ab2a65d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
